#!/usr/bin/env python3

"""
Regenerate data/railways.json from OpenStreetMap via the Overpass API.

Queries railway=rail within a bounding box around Grand Rapids, MI, then keeps
only ways with at least one vertex within MAX_MILES_FROM_CENTER mi of downtown.
Used by `#/visit` to inflate grid-walk distances when a pedestrian path would
cross active rail lines (no direct shortcut across the tracks).

Data © OpenStreetMap contributors, ODbL — https://www.openstreetmap.org/copyright
"""

from __future__ import annotations

import json
import math
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

# Grand Rapids metro-ish bbox: south, west, north, east (WGS84)
DEFAULT_BBOX = (42.85, -85.88, 43.12, -85.45)

GR_CENTER_LAT = 42.96333
GR_CENTER_LON = -85.66806
MAX_MILES_FROM_CENTER = 1.75

OVERPASS_URL = "https://overpass-api.de/api/interpreter"
REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_RAILWAYS = REPO_ROOT / "data/railways.json"

USER_AGENT = "multimodality-fetch-railways/1.0 (+https://github.com/citizenlabs/multimodality)"


def overpass_query(south: float, west: float, north: float, east: float) -> str:
    return f"""[out:json][timeout:120];
(
  way["railway"="rail"]({south},{west},{north},{east});
);
out geom tags;
"""


def haversine_miles(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    to_rad = math.pi / 180.0
    r = 3959.0
    d_lat = (lat2 - lat1) * to_rad
    d_lon = (lon2 - lon1) * to_rad
    a = math.sin(d_lat / 2) ** 2 + math.cos(lat1 * to_rad) * math.cos(
        lat2 * to_rad
    ) * math.sin(d_lon / 2) ** 2
    return r * 2 * math.atan2(math.sqrt(a), math.sqrt(max(0.0, 1 - a)))


def point_within_gr_center(lat: float, lon: float) -> bool:
    return (
        haversine_miles(lat, lon, GR_CENTER_LAT, GR_CENTER_LON)
        <= MAX_MILES_FROM_CENTER
    )


def way_within_gr_center(geometry: list[dict]) -> bool:
    for g in geometry:
        lat, lon = g.get("lat"), g.get("lon")
        if lat is None or lon is None:
            continue
        if point_within_gr_center(float(lat), float(lon)):
            return True
    return False


def element_to_line(el: dict) -> dict | None:
    if el.get("type") != "way":
        return None
    geometry = el.get("geometry")
    if not isinstance(geometry, list) or len(geometry) < 2:
        return None
    if not way_within_gr_center(geometry):
        return None
    coords = []
    for g in geometry:
        lat, lon = g.get("lat"), g.get("lon")
        if lat is None or lon is None:
            return None
        coords.append({"latitude": float(lat), "longitude": float(lon)})
    tags = el.get("tags") if isinstance(el.get("tags"), dict) else {}
    name = tags.get("name")
    out: dict = {"coordinates": coords}
    if isinstance(name, str) and name.strip():
        out["name"] = name.strip()
    return out


def http_post_overpass(query: str) -> dict:
    body = urllib.parse.urlencode({"data": query}).encode("utf-8")
    req = urllib.request.Request(
        OVERPASS_URL,
        data=body,
        method="POST",
        headers={
            "User-Agent": USER_AGENT,
            "Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
        },
    )
    with urllib.request.urlopen(req, timeout=180) as resp:
        return json.loads(resp.read().decode("utf-8"))


def main() -> int:
    south, west, north, east = DEFAULT_BBOX
    if len(sys.argv) == 5:
        try:
            south, west, north, east = (float(sys.argv[i]) for i in range(1, 5))
        except ValueError:
            print(
                "Usage: fetch_railways.py [south west north east]",
                file=sys.stderr,
            )
            return 1
    elif len(sys.argv) != 1:
        print(
            "Usage: fetch_railways.py [south west north east]",
            file=sys.stderr,
        )
        return 1

    query = overpass_query(south, west, north, east)
    try:
        data = http_post_overpass(query)
    except (urllib.error.URLError, json.JSONDecodeError, TimeoutError) as e:
        print(f"Overpass request failed: {e}", file=sys.stderr)
        return 1

    if data.get("remark"):
        print(f"Overpass remark: {data['remark']}", file=sys.stderr)

    lines: list[dict] = []
    for el in data.get("elements") or []:
        line = element_to_line(el)
        if line:
            lines.append(line)

    lines.sort(
        key=lambda ln: (
            (ln.get("name") or "").lower(),
            ln["coordinates"][0]["latitude"],
            ln["coordinates"][0]["longitude"],
        )
    )

    note = (
        "Generated by scripts/fetch_railways.py from OpenStreetMap "
        "(railway=rail) via Overpass API. "
        f"Ways are kept when any vertex lies within {MAX_MILES_FROM_CENTER:g} mi of "
        f"downtown Grand Rapids ({GR_CENTER_LAT:.5f}, {GR_CENTER_LON:.5f}). "
        "Data © OpenStreetMap contributors, ODbL — https://www.openstreetmap.org/copyright"
    )
    doc = {
        "name": "Railroad lines",
        "note": note,
        "lines": lines,
    }

    OUT_RAILWAYS.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(lines)} rail lines -> {OUT_RAILWAYS.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
